name: YAML-Validation

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      # - '!main'
    # paths:
    #   - 'my_yamls/**.yaml'
    #   - 'my_yamls/**.yml'

      # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-modified-yamls:
    name: Get Modified YAMLs
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: |
          echo 'hi'
          echo ${{ steps.files.outputs }}
        #   readarray -t removed_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.removed }}')"
        #   for removed_file in ${removed_files[@]}; do
        #   echo "Do something with this ${removed_file}."
        #   done

    #   - name: Get All Changed Files      
    #     uses: jitterbit/get-changed-files@v1
    #     run: |
    #       readarray -t removed_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.removed }}')"
    #       for removed_file in ${removed_files[@]}; do
    #       echo "Do something with this ${removed_file}."
    #       done

#       - name: Get Modified YAMLs
#         id: get-modified-yamls
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - name: run-git-diff
#         run: |
#           echo "git version: $(git --version)"
#           echo "git branch -r: $(git branch -r)"
#           echo "github.ref: ${{ github.ref }}"
#           echo "github.ref_name: ${{ github.ref_name }}"
#           CHANGED_FILES=$(git diff --name-only origin/main -- my_yamls/)
#           echo $CHANGED_FILES
#           echo "CHANGED_FILES=$CHANGED_FILES" >> "$GITHUB_OUTPUT"
#   show-modified-yamls:
#     name: Show Modified YAMLs
#     runs-on: ubuntu-latest
#     needs: get-modified-yamls
#     steps:
#       - name: Show Modified YAMLs
#         id: show-modified-yamls
#         env: 
#           CHANGED_FILES: ${{ needs.get-modified-yamls.outputs.CHANGED_FILES }}
#         run: |
#           echo "changed files: $CHANGED_FILES"



# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v4

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
